### ISSUE TITLE
Support for IPv6 lookups

### ISSUE THREAD

**Issue by ricardo-rod** [ventz/docker-dns-over-https#1] opened 2019-06-19 18:55 UTC
Could you please change the ns statement  LocalAddr => [ '0.0.0.0' ], to ['::'], in that way I think maybe it will take ipv6 petitions.

**Comment by ventz** [comment] 2019-06-20 04:11
@Rrvz Thanks for pointing this out - I added as an option and pushed out (see last 2 commits)

The reason I added it as an option is because on non-IPv6 stacked systems (or non-IPv6 configured docker configs) it produces an error. This is actually caused by the `Net::DNS::Nameserver` package not handling this condition well and "crashing" the IPv6 listener instead of just silently moving on and just reporting it as an information print.

Let me know if this works.

UPDATE: Tested it out - seems to work

**Comment by ventz** [comment] 2019-07-06 18:22
Closing -- please feel free to re-open if you think there's something else that should be updated in regards to the IPv6.

**Closed as completed by ventz** 2019-07-06 18:22 UTC
